" folders
set wildignore+=public\/build
set wildignore+=source_maps
set wildignore+=coverage
set wildignore+=node_modules
set wildignore+=*/tmp/*

" filetypes
set wildignore+=*.o
set wildignore+=.git
set wildignore+=*.jpg
set wildignore+=*.png
set wildignore+=*.swp
set wildignore+=*.d
set wildignore+=*.gif
set wildignore+=*.pyc
set wildignore+=*.class
set wildignore+=*.crf
set wildignore+=*.hg
set wildignore+=*.orig
set wildignore+=.meteor
